"""add company_permissions

Revision ID: 703fb3460d5a
Revises: ee841556577c
Create Date: 2026-04-07 17:48:18.639380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '703fb3460d5a'
down_revision: Union[str, Sequence[str], None] = 'ee841556577c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('staff_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_permissions_company_id'), 'company_permissions', ['company_id'], unique=True)
    op.create_index(op.f('ix_company_permissions_id'), 'company_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_manual_invoices_client_id'), 'manual_invoices', ['client_id'], unique=False)
    op.drop_constraint(op.f('manual_invoices_updated_by_user_id_fkey'), 'manual_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'manual_invoices', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('manual_invoices_updated_by_user_id_fkey'), 'manual_invoices', 'users', ['updated_by_user_id'], ['id'])
    op.drop_index(op.f('ix_manual_invoices_client_id'), table_name='manual_invoices')
    op.drop_index(op.f('ix_company_permissions_id'), table_name='company_permissions')
    op.drop_index(op.f('ix_company_permissions_company_id'), table_name='company_permissions')
    op.drop_table('company_permissions')
    # ### end Alembic commands ###
