"""add site maps and monitoring visits

Revision ID: 9b142ca56ce2
Revises: 518ac65c417d
Create Date: 2026-04-04 16:56:14.929660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b142ca56ce2'
down_revision: Union[str, Sequence[str], None] = '518ac65c417d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('page_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_maps_client_id'), 'site_maps', ['client_id'], unique=False)
    op.create_index(op.f('ix_site_maps_company_id'), 'site_maps', ['company_id'], unique=False)
    op.create_index(op.f('ix_site_maps_id'), 'site_maps', ['id'], unique=False)
    op.create_table('site_map_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_map_id', sa.Integer(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('x_percent', sa.Float(), nullable=False),
    sa.Column('y_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_map_id'], ['site_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_map_points_id'), 'site_map_points', ['id'], unique=False)
    op.create_index(op.f('ix_site_map_points_site_map_id'), 'site_map_points', ['site_map_id'], unique=False)
    op.create_table('monitoring_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('pest_type', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_visits_appointment_id'), 'monitoring_visits', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_monitoring_visits_client_id'), 'monitoring_visits', ['client_id'], unique=False)
    op.create_index(op.f('ix_monitoring_visits_company_id'), 'monitoring_visits', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitoring_visits_id'), 'monitoring_visits', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_visits_user_id'), 'monitoring_visits', ['user_id'], unique=False)
    op.create_table('monitoring_point_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('site_map_point_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=20), nullable=True),
    sa.Column('consumption_percent', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('replaced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_map_point_id'], ['site_map_points.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['monitoring_visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_point_results_id'), 'monitoring_point_results', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_point_results_site_map_point_id'), 'monitoring_point_results', ['site_map_point_id'], unique=False)
    op.create_index(op.f('ix_monitoring_point_results_visit_id'), 'monitoring_point_results', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_point_results_visit_id'), table_name='monitoring_point_results')
    op.drop_index(op.f('ix_monitoring_point_results_site_map_point_id'), table_name='monitoring_point_results')
    op.drop_index(op.f('ix_monitoring_point_results_id'), table_name='monitoring_point_results')
    op.drop_table('monitoring_point_results')
    op.drop_index(op.f('ix_monitoring_visits_user_id'), table_name='monitoring_visits')
    op.drop_index(op.f('ix_monitoring_visits_id'), table_name='monitoring_visits')
    op.drop_index(op.f('ix_monitoring_visits_company_id'), table_name='monitoring_visits')
    op.drop_index(op.f('ix_monitoring_visits_client_id'), table_name='monitoring_visits')
    op.drop_index(op.f('ix_monitoring_visits_appointment_id'), table_name='monitoring_visits')
    op.drop_table('monitoring_visits')
    op.drop_index(op.f('ix_site_map_points_site_map_id'), table_name='site_map_points')
    op.drop_index(op.f('ix_site_map_points_id'), table_name='site_map_points')
    op.drop_table('site_map_points')
    op.drop_index(op.f('ix_site_maps_id'), table_name='site_maps')
    op.drop_index(op.f('ix_site_maps_company_id'), table_name='site_maps')
    op.drop_index(op.f('ix_site_maps_client_id'), table_name='site_maps')
    op.drop_table('site_maps')
    # ### end Alembic commands ###
